name: dbwe
dependencies:
  - python==3.10.*
  - conda==23.5.*
  - pip==23.1.*
  - pip:
      - ipykernel==6.24.*
      - numpy==1.25.*
      - matplotlib==3.7.*
      - openpyxl==3.1.*
      - pylint==2.17.*
      - pyjwt==2.1.*
      - mariadb==1.1.*
      - Flask==2.3.*
      - wtforms==3.0.*
      - flask_wtf==1.1.*
      - flask-sqlalchemy==3.0.*
      - flask-migrate==4.0.*
      - flask-login==0.6.*
      - flask-mail==0.9.*
      - flask-bootstrap==3.3.7.1
      - flask-httpauth==4.4.0
      - werkzeug==2.3.*
      - email-validator==2.0.*